# Generated by Django 2.2.5 on 2022-03-17 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_auto_20220317_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='funding',
            name='music_type',
        ),
        migrations.AddField(
            model_name='funding',
            name='music_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundings.MusicType'),
        ),
        migrations.AddField(
            model_name='funding',
            name='amenities',
            field=models.ManyToManyField(to='fundings.Amenity'),
        ),
        migrations.AddField(
            model_name='funding',
            name='facilities',
            field=models.ManyToManyField(to='fundings.Facility'),
        ),
        migrations.AddField(
            model_name='funding',
            name='house_rules',
            field=models.ManyToManyField(to='fundings.HouseRule'),
        ),
    ]
