# Generated by Django 2.2.5 on 2022-03-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0003_auto_20220317_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name': 'House Rule'},
        ),
        migrations.AlterModelOptions(
            name='musictype',
            options={'verbose_name': 'Music Type'},
        ),
        migrations.AlterField(
            model_name='funding',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='fundings.Amenity'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='fundings.Facility'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='house_rules',
            field=models.ManyToManyField(blank=True, to='fundings.HouseRule'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundings.Funding')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
