# Generated by Django 2.2.5 on 2022-03-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0006_auto_20220325_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fundings.Funding'),
        ),
    ]
