# Generated by Django 2.2.5 on 2022-03-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0007_auto_20220325_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='music_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundings', to='fundings.MusicType'),
        ),
    ]
