# Generated by Django 2.2.5 on 2022-03-29 07:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0009_auto_20220329_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='funding',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='price',
            field=models.IntegerField(),
        ),
    ]
