# Generated by Django 2.2.5 on 2022-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0011_auto_20220402_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='check_out',
            field=models.DateField(),
        ),
    ]
