# Generated by Django 2.2.5 on 2022-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0013_auto_20220402_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funding',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='funding_photos'),
        ),
    ]
