# Generated by Django 2.2.5 on 2022-04-12 05:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0016_auto_20220412_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
