# Generated by Django 2.2.5 on 2022-05-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0017_funding_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='musics/')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='fundings.Funding')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
