# Generated by Django 2.2.5 on 2022-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0018_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='musics/'),
        ),
    ]
