# Generated by Django 2.2.5 on 2022-05-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0019_auto_20220510_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='sfile',
        ),
    ]
