# Generated by Django 2.2.5 on 2022-06-10 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundings', '0020_auto_20220510_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buy_share', models.IntegerField()),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='fundings.Funding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
