# Generated by Django 2.2.5 on 2022-03-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20220325_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='funding_end',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='funding_start',
            new_name='check_out',
        ),
    ]
