# Generated by Django 2.2.5 on 2022-04-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20220329_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in',
            new_name='funding_end',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_out',
            new_name='funding_start',
        ),
    ]
