# Generated by Django 2.2.5 on 2022-03-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0009_auto_20220329_1624'),
        ('reviews', '0002_auto_20220325_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='funding',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fundings.Funding'),
            preserve_default=False,
        ),
    ]
