# Generated by Django 2.2.5 on 2022-03-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20220329_1612'),
        ('reviews', '0003_review_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='musics.Music'),
            preserve_default=False,
        ),
    ]
