# Generated by Django 2.2.5 on 2022-03-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='funding',
        ),
    ]
