# Generated by Django 2.2.5 on 2022-06-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_funding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',)},
        ),
    ]
