# Generated by Django 2.2.5 on 2022-03-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20220325_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='musics.MusicType'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='musics.Music'),
        ),
    ]
