# Generated by Django 2.2.5 on 2022-04-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20220412_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Music Type',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='music_type',
            field=models.ManyToManyField(blank=True, related_name='musics', to='musics.MusicType'),
        ),
    ]
