# Generated by Django 2.2.5 on 2022-06-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
