# Generated by Django 2.2.5 on 2022-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_auto_20220607_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='price',
            field=models.IntegerField(),
        ),
    ]
