# Generated by Django 2.2.5 on 2022-04-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20220406_1856'),
        ('lists', '0002_auto_20220325_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='fundings',
        ),
        migrations.AddField(
            model_name='list',
            name='musics',
            field=models.ManyToManyField(blank=True, related_name='lists', to='musics.Music'),
        ),
    ]
